title: Thoughts - Processed
author: erictrem
email: redacted@0xECC8.com
description: > # this means to ignore newlines until "baseurl:"
  This is a bland description.


# social links
twitter_username: erictrem # DO NOT include the @ character, or else the build will fail!
github_username:  erictrem # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

